version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment: 
  pfx_password: 
    secure: utd0GjRa0oZl52ooFprYZQ==
  snk_password: 
    secure: dut1MSCvW/OF6CkOugqpZNH0WAhVFPj6CN6xBRx5BmE=
init:
  - ps: 'Update-AppveyorBuild -Version "1.1.$env:appveyor_build_number.$([math]::Truncate(((Get-Date) - (Get-Date -Year 2016 -Month 1 -Day 1 -Hour 0 -Minute 0 -Second 0)).TotalDays))"'
install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt ErrorReporter.Core/ErrorReporter.Core.snk.enc -secret %snk_password%    
  - secure-file\tools\secure-file -decrypt ErrorReporter.Sentry/ErrorReporter.Sentry.snk.enc -secret %snk_password%    
  - secure-file\tools\secure-file -decrypt ErrorReporter.DeadmansSnitch/ErrorReporter.DeadmansSnitch.snk.enc -secret %snk_password%    
before_build:
- cmd: nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


build:
  project: ErrorReporter.sln
  publish_nuget: true

artifacts:
- path: bin\$(configuration)\*.nupkg
  name: NuGet Package
  
deploy:
- provider: NuGet
  api_key:
    secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+

#before_package:
#  - ps: .\ci-scripts\set-package-version-using-branch.ps1 -nuspec ErrorReporter.Core\ErrorReporter.Core.nuspec -baseVersion $env:appveyor_build_version -branchName $env:appveyor_repo_branch -releaseBranchName release